global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
- job_name: ndc_segment
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - ndc_segment:3001
