version: "3"

volumes:
    prometheus_data: {}
    
services:
  localstack:
    image: atlassianlabs/localstack
    ports:
      - "4573:4573"
      - "8080:8080"
    environment:
      - SERVICES=firehose

  ndc_segment:
    image: brightsparc/ndc_segment
    links:
      - localstack
    ports:
      - "3001:3001"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    links:
      - ndc_segment
    ports:
      - "9090:9090"
