version: "3"

services:
  localstack:
    image: atlassianlabs/localstack
    ports:
      - "4573:4573"
      - "8080:8080"
    environment:
      - SERVICES=firehose

  ndc_segment:
    image: brightsparc/ndc_segment
    links:
      - localstack
    ports:
      - "3001:3001"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
